### ISSUE TITLE
NodeJS 17.x

### ISSUE THREAD

**Issue by freasy** [ExpressLRS/ExpressLRS-Configurator#331]
When trying to initialize development on node 17, it cant be built.
Webpack runs into this:
```bash
[4/4] Building fresh packages...
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && yarn-deduplicate yarn.lock
  • electron-builder  version=22.14.5
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/eike/dev/freasy/ExpressLRS-Configurator/src
yarn run v1.22.18
$ yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
$ /home/eike/dev/freasy/ExpressLRS-Configurator/node_modules/.bin/cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
asset renderer.dev.dll.js 39.3 MiB [emitted] (name: renderer)
12393 modules

WARNING in ./node_modules/electron-debug/index.js 109:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[11]

WARNING in ./node_modules/electron-debug/index.js 110:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[11]

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js 22:11-28
 @ ./node_modules/express/lib/express.js 18:12-36
 @ ./node_modules/express/index.js 11:0-41
 @ dll renderer renderer[14]

WARNING in ./node_modules/type-graphql/dist/helpers/loadResolversFromGlob.js 11:46-63
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/type-graphql/dist/utils/buildSchema.js 6:32-75
 @ ./node_modules/type-graphql/dist/utils/index.js 4:20-44
 @ ./node_modules/type-graphql/dist/index.js 10:21-39
 @ dll renderer renderer[36]

ERROR in ./node_modules/@fontsource/roboto/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/@fontsource/roboto/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package subpath './package.json' is not defined by "exports" in /home/eike/dev/freasy/ExpressLRS-Configurator/node_modules/css-loader/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/home/eike/dev/freasy/ExpressLRS-Configurator/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/eike/dev/freasy/ExpressLRS-Configurator/node_modules/css-loader/dist/index.js:12:39)
 @ ./node_modules/@fontsource/roboto/index.css 2:12-105 9:17-24 13:15-29
 @ dll renderer renderer[3]

webpack 5.5.1 compiled with 1 error and 4 warnings in 15035 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by jurgelenas** [comment]
ExpressLRS Configurator does not support non-LTS node.js versions for the development. 

@freasy you could try downgrading node.js to v16.

**Comment by freasy** [comment]
Yes i did that, and its running fine. I just thought to inform, that 17 isnt working currently.
