### ISSUE TITLE
Jumper T Pro Internal ExpressLRS module update problem

### ISSUE THREAD

**Issue by JazzSutrisno** [ExpressLRS/ExpressLRS-Configurator#332]
## Summary
Hi, I just bought a Jumper T Pro Internal ExpressLRS module, I wanted to update to 2.2.0 releases with ExpressLRS Configurator v1.3.11
after i press "build" the log says "failed to create process". the jumper still fine (not brick) though.

![elrs update 1](https://user-images.githubusercontent.com/104815552/166420972-e0ade782-991a-4202-9792-a2df33953fc7.jpg)
![elrs update 2](https://user-images.githubusercontent.com/104815552/166421013-8e6a9e1b-e3c6-4f22-bad0-832bf667cb80.jpg)

any solution?

**Comment by jurgelenas** [comment]
@JazzSutrisno  can you add logs file from log tab over here?

Are you using 64bit windows? What is your windows version? Are you using different kind of operating system?

You could try disabling your firewall / antivirus.

**Comment by JazzSutrisno** [comment]
@jurgelenas sorry for the late reply mate.
yes i use 64bit windows 10
disabling firewall/antivirus is not solving
and here is the log. 
[expressslrs-configurator.log](https://github.com/ExpressLRS/ExpressLRS-Configurator/files/8645000/expressslrs-configurator.log)

**Comment by GutoFleury** [comment]
I cant build for my Jumper T-pro.

Logs:

Please wait while upgrading PlatformIO...
Error: Traceback (most recent call last):
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio_main_.py", line 102, in main
cli() # pylint: disable=no-value-for-parameter
^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 1130, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\commands_init_.py", line 44, in invoke
return super().invoke(ctx)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 1654, in invoke
super().invoke(ctx)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\contextlib.py", line 155, in exit
self.gen.throw(typ, value, traceback)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 101, in augment_usage_errors
yield
^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\core.py", line 760, in invoke
return _callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\click\decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio_main.py", line 56, in cli
maintenance.on_platformio_start(ctx, force, caller)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\maintenance.py", line 43, in on_platformio_start
after_upgrade(ctx)
^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\maintenance.py", line 155, in after_upgrade
cleanup_content_cache("http")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\cache.py", line 164, in cleanup_content_cache
with ContentCache(namespace) as cc:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\cache.py", line 36, in enter
self.delete()
^^^^^^^^^^^^^
File "C:\Users\gutof.platformio\penv\Lib\site-packages\platformio\cache.py", line 132, in delete
with open(self._db_path, mode="w", encoding="utf8") as fp:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\Users\gutof\.platformio\.cache\http\db.data'

============================================================

An unexpected error occurred. Further steps:

Verify that you have the latest version of PlatformIO using
pip install -U platformio command

Try to find answer in FAQ Troubleshooting section
https://docs.platformio.org/page/faq.html

Report this problem to the developers
https://github.com/platformio/platformio-core/issues

===========================================================

**Comment by JazzSutrisno** [comment]
@jurgelenas  Thats okay, thank you for trying and the suggestion. cheers 👍
