### ISSUE TITLE
How to produce firmware file for web upload [2.5.0. works, earlier versions dont] 

### ISSUE THREAD

**Issue by MartinHugh** [ExpressLRS/ExpressLRS-Configurator#344]
I am trying to update the firmware on a HappyModel ES24TX 2400 TX, from 2.0.0 to 2.2.0
The way I usually do an update is to produce the firmware as a file. I can then reuse it if necessary without having to recompile.
However, I seem to be having problems ever since installing 1.4.1

EDIT : In fact this not only fails to build 2.2.0, it also fails to build 2.3.0 and 2.4.0.
          2.5.0 builds fine.

Using Configurator 1.4.1

If I select UART update and press "Build" I get 

```
Building in release mode
Installing pexpectCollecting streamexpect
  Using cached streamexpect-0.2.1.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  � python setup.py egg_info did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
File "C:\Users\mhrpc\AppData\Local\Temp\pip-install-i46v4_aj\streamexpect_d03d9fbc10c042ccb03408265f580bc6\setup.py", line 20, in <module>
          setup(
          ^^^^^^
        File "C:\Users\mhrpc\.platformio\penv\Lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mhrpc\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\mhrpc\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 453, in __init__
          _Distribution.__init__(
          ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mhrpc\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
          ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mhrpc\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 831, in finalize_options
          ep(self)
          ^^^^^^^^
        File "C:\Users\mhrpc\.platformio\penv\Lib\site-packages\setuptools\dist.py", line 852, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\mhrpc\appdata\local\temp\pip-install-i46v4_aj\streamexpect_d03d9fbc10c042ccb03408265f580bc6\.eggs\setuptools_markdown-0.4.1-py3.11.egg\setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
                   ^^^^^^^^^^^^^^^^
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

� Encountered error while generating package metadata.
\u2570\u2500> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
CalledProcessError: Command '['C:\\Users\\mhrpc\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', 'streamexpect']' returned non-zero exit status 1.:
  File "C:\Users\mhrpc\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 192:
    env.SConscript(item, exports="env")
  File "C:\Users\mhrpc\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\mhrpc\.platformio\packages\tool-scons\scons-local-4.3.0\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\mhrpc\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\build_env_setup.py", line 7:
    import ETXinitPassthrough
  File "C:\Users\mhrpc\AppData\Roaming\ExpressLRS Configurator\firmwares\github\ExpressLRS\src\python\ETXinitPassthrough.py", line 14:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "streamexpect"])
  File "C:\Users\mhrpc\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\Lib\subprocess.py", line 369:
    raise CalledProcessError(retcode, cmd)
========================= [FAILED] Took 36.19 seconds =========================

Environment                         Status    Duration
----------------------------------  --------  ------------
HappyModel_ES24TX_2400_TX_via_UART  FAILED    00:00:36.185
==================== 1 failed, 0 succeeded in 00:00:36.185 ====================

```

Any suggestions please ?

**Comment by MartinHugh** [comment]
Closing this, as @deadbyte has pointed me to 
https://github.com/ExpressLRS/ExpressLRS/pull/1564
and use of an alternative source tree to master.
