### ISSUE TITLE
Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.

### ISSUE THREAD

**Issue by Dragony** [ExpressLRS/ExpressLRS-Configurator#379]
## Expected Behavior

I should be able to compile a firmware build.

## Current Behavior

I can't compile any firmware version. I have previously compiled many builds on the same PC with the same installation. Starting today I'm getting the following error when I build:

```
Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.0
Platform: Windows-10
Python version: 3.11.0a4 (main, Jan 17 2022, 13:12:23) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python-3.11.0a4.amd64\python3.exe
Creating a virtual environment at C:\Users\drago\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/platformio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/platformio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/platformio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/platformio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/platformio/
ERROR: Could not find a version that satisfies the requirement platformio (from versions: none)
ERROR: No matching distribution found for platformio
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\drago\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
 ```
I have already tried deleting the platform IO dependencies.

## Steps to Reproduce

(On my PC) select any build for any target and click compile.

## Possible Solution (Not obligatory)

possible dependency issue? python conflict?

## Context

As mentioned previsouly I was previously able to combile builds on this pc with this exact version and installation. I assume it might be some sort of dependency issue.

## Your Environment

- Operating System and version: Windows 10, Version 21H2 (OS Build 19044.1889)
- Locally installed python version: Python 3.9.13 (but the logs says it's using 3.11)
- TX hardware: n/a
- RX hardware: n/a

**Comment by jurgelenas** [comment]
Try 1.5.0 configurator version.

**Comment by Dragony** [comment]
New Error, but still can't build. I've tried clearning platformIO. Should I reinstall the Configurator?

```
Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe
Creating a virtual environment at C:\Users\drago\.platformio\penv
C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe
Traceback (most recent call last):
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 386, in _make_request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 1040, in _validate_conn
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connection.py", line 395, in connect
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\util\ssl_.py", line 350, in create_urllib3_context
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\adapters.py", line 440, in send
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 785, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\util\retry.py", line 550, in increment
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\packages\six.py", line 769, in reraise
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 386, in _make_request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connectionpool.py", line 1040, in _validate_conn
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\connection.py", line 395, in connect
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\urllib3\util\ssl_.py", line 350, in create_urllib3_context
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 67, in <module>
    main()
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 59, in main
    bootstrap()
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 45, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\penv.py", line 58, in create_core_penv
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\python.py", line 70, in fetch_portable_python
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\pioinstaller\python.py", line 97, in get_portable_python_url
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\api.py", line 75, in get
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\api.py", line 61, in request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\sessions.py", line 529, in request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\sessions.py", line 645, in send
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-0jpbbbcf\tmplg29dm85\pioinstaller.zip\requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
