### ISSUE TITLE
Cannot build on Windows 10: No such file or directory: 'C:\\'

### ISSUE THREAD

**Issue by Dragony** [ExpressLRS/ExpressLRS-Configurator#386]
This is a followup for: https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/379

## Expected Behavior

I should be able to build a firmware.

## Current Behavior

I can't build any firmware version, platformIO install fails.

## Steps to Reproduce

Fresh install on Windows 10.

## Possible Solution (Not obligatory)

I assume something is wrong in the install script for platformIO.

## Context

Stacktrace:

```
Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Python path: C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe
Creating a virtual environment at C:\Users\drago\.platformio\penv
C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe
Traceback (most recent call last):
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 386, in _make_request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 1040, in _validate_conn
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connection.py", line 395, in connect
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\util\ssl_.py", line 350, in create_urllib3_context
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\adapters.py", line 440, in send
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 785, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\util\retry.py", line 550, in increment
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\packages\six.py", line 769, in reraise
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 386, in _make_request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connectionpool.py", line 1040, in _validate_conn
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\connection.py", line 395, in connect
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\urllib3\util\ssl_.py", line 350, in create_urllib3_context
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 67, in <module>
    main()
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 59, in main
    bootstrap()
  File "C:\Users\drago\AppData\Local\Programs\ExpressLRS Configurator\dependencies\get-platformio.py", line 45, in bootstrap
    pioinstaller.__main__.main()
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\__main__.py", line 133, in main
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\core.py", line 1128, in __call__
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\core.py", line 1053, in main
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\core.py", line 1637, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\core.py", line 1395, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\core.py", line 754, in invoke
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\click\decorators.py", line 26, in new_func
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\__main__.py", line 61, in cli
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\core.py", line 70, in install_platformio_core
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\core.py", line 98, in _install_platformio_core
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\penv.py", line 58, in create_core_penv
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\python.py", line 70, in fetch_portable_python
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\pioinstaller\python.py", line 97, in get_portable_python_url
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\api.py", line 75, in get
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\api.py", line 61, in request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\sessions.py", line 529, in request
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\sessions.py", line 645, in send
  File "C:\Users\drago\AppData\Roaming\ExpressLRS Configurator\.piocore-installer-8634slad\tmpiepij9br\pioinstaller.zip\requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

## Your Environment

- Tried running as Admin, doesn't help
- ExpressLRS Configurator is installed on C:
- I tried a fresh reinstall, including removing platformIO dependencies
- Operating System and version: Windows 10, Version 21H2 (OS Build 19044.1889)
- TX hardware: n/a
- RX hardware: n/a

**Comment by Dragony** [comment]
Problem solved, it was an Issue with the urllib3 library. I had to remove the environment variable `SSLKEYLOGFILE` from my system. Now platformIO installs as expected.
