### ISSUE TITLE
Issues building on ubuntu 22.04

### ISSUE THREAD

**Issue by hurnhu** [ExpressLRS/ExpressLRS-Configurator#395]
## Expected Behavior
When I click build it should build my RX firmware

## Current Behavior
Crashing when trying to build

## Steps to Reproduce

pre-req: be on ubuntu 22.04.
before updating to 22.04 i was able to build just fine.

`Installing pexpectCollecting streamexpect
  Using cached streamexpect-0.2.1.tar.gz (13 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j99ophlb/streamexpect_5a80fa66e84547ef877b2d8e59c735cf/setup.py", line 20, in <module>
          setup(
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/home/michael/.platformio/penv/lib/python3.10/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-install-j99ophlb/streamexpect_5a80fa66e84547ef877b2d8e59c735cf/.eggs/setuptools_markdown-0.4.1-py3.10.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
CalledProcessError: Command '['/home/michael/.platformio/penv/bin/python', '-m', 'pip', 'install', 'streamexpect']' returned non-zero exit status 1.:
  File "/home/michael/.platformio/penv/lib/python3.10/site-packages/platformio/builder/main.py", line 196:
    env.SConscript(item, exports="env")
  File "/home/michael/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/michael/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/michael/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/build_env_setup.py", line 7:
    import ETXinitPassthrough
  File "/home/michael/.config/ExpressLRS Configurator/firmwares/github/ExpressLRS/src/python/ETXinitPassthrough.py", line 14:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "streamexpect"])
  File "/usr/lib/python3.10/subprocess.py", line 369:
    raise CalledProcessError(retcode, cmd)
========================== [FAILED] Took 8.44 seconds ==========================
Environment                                           Status    Duration
----------------------------------------------------  --------  ------------
DIY_2400_RX_ESP8285_SX1280_via_BetaflightPassthrough  FAILED    00:00:08.444
==================== 1 failed, 0 succeeded in 00:00:08.444 ====================
`

## Your Environment

Ubuntu 22.04

**Comment by hurnhu** [comment]
WORK AROUND:

install python3.8
then run python3.8  -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
