### ISSUE TITLE
module argparse missing

### ISSUE THREAD

**Issue by s0i37** [ExpressLRS/ExpressLRS-Configurator#413]
The error has occuried during `build` firmware

```
Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.2
Platform: Linux-5.4.8-rt3-x86_64-with-glibc2.33
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Python path: /usr/bin/python3
Creating a virtual environment at /home/soier/.platformio/penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
ERROR: Exception:
Traceback (most recent call last):
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 287, in run
    session = self.get_default_session(options)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 75, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session
    session = PipSession(
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 282, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 120, in user_agent
    from pip._vendor import distro
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_vendor/distro/__init__.py", line 1, in <module>
    from .distro import (
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_vendor/distro/distro.py", line 31, in <module>
    import argparse
ModuleNotFoundError: No module named 'argparse'
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 144, in handle_pip_version_check
    session = self._build_session(
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session
    session = PipSession(
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 282, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 120, in user_agent
    from pip._vendor import distro
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_vendor/distro/__init__.py", line 1, in <module>
    from .distro import (
  File "/home/soier/.platformio/penv/lib/python3.9/site-packages/pip/_vendor/distro/distro.py", line 31, in <module>
    import argparse
ModuleNotFoundError: No module named 'argparse'
Error: Could not install PlatformIO Core: Command '['/home/soier/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.
```

**Comment by jurgelenas** [comment]
I think there is something wrong with your Python environment. `argparse` is a standard library that comes bundled with python.
