### ISSUE TITLE
ImportError: DLL load failed while importing unicodedata

### ISSUE THREAD

**Issue by LukaOo** [ExpressLRS/ExpressLRS-Configurator#440]
## When try to "build and flash" TX during verifying build system got error "Platformio dependency error"
Next log message in dump: 

`Failed to find Platformio on your computer. Trying to install it automatically...Installer version: 1.1.2
Platform: Windows-10
Python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Python path: D:\Programs\ExpressLRS Configurator\dependencies\windows_amd64\python\python3.exe
Creating a virtual environment at C:\Users\\.platformio\penv
Updating Python package manager (PIP) in a virtual environment
Virtual environment has been successfully created!
Installing PlatformIO Core
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
    """Execute a module's code without importing it
  File "runpy.py", line 87, in _run_code
    
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_internal\build_env.py", line 16, in <module>
    from pip._vendor.packaging.requirements import Requirement
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 10, in <module>
    from pip._vendor.pyparsing import (  # noqa
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_vendor\pyparsing\__init__.py", line 138, in <module>
    from .exceptions import *
  File "C:\Users\\.platformio\penv\lib\site-packages\pip\_vendor\pyparsing\exceptions.py", line 8, in <module>
    from .unicode import pyparsing_unicode as ppu
ImportError: DLL load failed while importing unicodedata: Specified path was not found.
Error: Could not install PlatformIO Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while.
 Command '['C:\\Users\\\\.platformio\\penv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1.`

## What was discovered
* Configurator creates python enviroment and inside python losts link with unicodedata.pyd.
* I also try launched pip inside original configurator's python path specified in head of the message. seems it works properly.  
* I roll back configurator to 1.5.0 and got same issue. After roll back to 1.4.2 i got log message "python dependency error"     

## OS, soft and hardware
- Operating System and version:  Windows 10. I have conda instalation with python 3.6 installed
- Configurator 1.5.3
- TX hardware : HAPPYMODEL ES24TX

**Comment by LukaOo** [comment]
Further problem's research discovered source of issues. There is conda installation and PYTHONHOME python environment variable was declared for current user. If  disable the environment variable error disappeared.

**Comment by jurgelenas** [comment]
Thanks for reporting this. I think this is a minor & rare issue, but I have fixed it in #445
