### ISSUE TITLE
Ошибка со сборкой прошивки вручном режиме

### ISSUE THREAD

**Issue by ViktorVohmin** [ExpressLRS/ExpressLRS-Configurator#584]
Can not remove temporary directory `E:\ExpressLRS\src\.pio\build`. Please remove it manually to avoid build issues

TypeError: Traceback (most recent call last):
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\cli.py", line 85, in invoke
    return super().invoke(ctx)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 145, in cli
    process_env(
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 191, in process_env
    print_processing_header(name, config, verbose)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\run\cli.py", line 232, in print_processing_header
    for k, v in config.items(env=env):
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 222, in items
    return [(option, self.get(section, option)) for option in self.options(section)]
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 222, in <listcomp>
    return [(option, self.get(section, option)) for option in self.options(section)]
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 380, in get
    value = self.getraw(section, option, default)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 312, in getraw
    return self._expand_interpolations(section, option, value)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 338, in _expand_interpolations
    return self.VARTPL_RE.sub(
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 339, in <lambda>
    lambda match: self._re_interpolation_handler(section, option, match), value
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 367, in _re_interpolation_handler
    value = self.get(section, option)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 380, in get
    value = self.getraw(section, option, default)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 289, in getraw
    return self._expand_interpolations(section, option, value)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 338, in _expand_interpolations
    return self.VARTPL_RE.sub(
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 339, in <lambda>
    lambda match: self._re_interpolation_handler(section, option, match), value
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 367, in _re_interpolation_handler
    value = self.get(section, option)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 380, in get
    value = self.getraw(section, option, default)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 281, in getraw
    option_meta = self.find_option_meta(section, option)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 252, in find_option_meta
    scope = self.get_section_scope(section)
  File "C:\Users\Viktor\.platformio\penv\lib\site-packages\platformio\project\config.py", line 167, in get_section_scope
    return section.split(":", 1)[0] if ":" in section else section
TypeError: argument of type 'NoneType' is not iterable

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

такого пути вообще нету
E:\ExpressLRS\src\.pio\build

**Comment by ViktorVohmin** [comment]
Update 

C:\Program Files\ExpressLRS Configurator\dependencies\windows_amd64\portablepy.ps1

old 
$source = 'https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-amd64.zip'

new
$source = 'https://www.python.org/ftp/python/3.11.0/python-3.11.0-embed-amd64.zip'

Run PowerShell  portablepy.ps1
